### PR TITLE
Trial Solution

### PR DESCRIPTION
**Pull request by SMcLaren09**
Needs to be debugged, this is based on several sample solutions on
github.

### CODE REVIEW

**Comment by dssquared** [comment]
I'll check it out soon, we just got back from a balloon flight. I've been
researching bin packing algos and fighting with getting pyhon 3 to play
nice with my other programs. I'll be working on it soon and i'll keep in
touch.

**Comment by SMcLaren09** [comment]
Believe me I understand. I found the example solution alex had posted. This
is based on that and several other examples on github. Basically start with
a large rectangle and keep decreasing its size.

The driver file is throwing errors for me. Ryan said it was updated on
github but not much luck with the updated one either.

This should be complete, I am not familiar enough with python to get all of
the syntax errors straightened out. I did get the block format figured out
and fixed.

Steph

**Comment by dssquared** [comment]
Current master empty, merged steph branch to master

**Comment by dssquared** [comment]
Hi Steph, I am going through and debugging the code now. I was having
trouble initially with the driver not running while using a couple
different IDEs and python 3.4. I could get it to run in IDLE but not in the
IDEs that I was using to write the code. I switched to Python3.5 and had to
force it to install in a different folder to get it to work. The driver.py
in the github repo will run with python3.5. The errors look worse than what
I think they are. Alex has four or more threads running and the same error
shows up in each thread so it looks like four different errors. Then in one
place it is throwing a divide by zero error. It might only be two things, I
don't know yet, I just wanted to get back to you and let you know I was
working on it. I will continue working on it now and I will keep ya posted.
I hope to be back in Bozeman tomorrow early evening, I will be working on
the bin packing as much as I can and In the car on my way back to town. We
have had a very busy week getting up early and staying up late but we had
two succefull balloon flights after a few hiccups. I hope to help as much
as I can and I feel bad I have not been more help, the timming just sucks
right now. The more I read about the strip packing problem the more fun I
think it would be to come up with an optimal solution.
Talk soon.
David

On Tue, Feb 16, 2016 at 6:21 PM, Stephanie McLaren <notifications@github.com
> wrote:

> Believe me I understand. I found the example solution alex had posted. This
> is based on that and several other examples on github. Basically start with
> a large rectangle and keep decreasing its size.
>
> The driver file is throwing errors for me. Ryan said it was updated on
> github but not much luck with the updated one either.
>
> This should be complete, I am not familiar enough with python to get all of
> the syntax errors straightened out. I did get the block format figured out
> and fixed.
>
> Steph
>
>

**Comment by SMcLaren09** [comment]
Doing the debugging is more than enough.

**Comment by SMcLaren09** [comment]
Stupid fat fingers on little phone!  I sent that before I finished my
thought. I wish we had more time as well. Paxton gave us reasonable time
but I am with you, the timing really sucks. Three major programming
projects all due at the same time "_"

Glad your flights went well. See you friday. Let me know if there is more I
can do.

Steph

**Comment by dssquared** [comment]
Leaving SD now. We have internet and my computer in the car so I can work
on the bin packing. I've narrowed it down to one last variable that is out
of scope then I can run the whole thing and hope there is not many runtime
errors. I'll push it to the repo as soon as I run it the first time I'll
keep in touch.

**Comment by SMcLaren09** [comment]
Class updates:

We should measure from upper left corner to upper right and then down. When
class is over I will check the code for that and set up a text file
outlining our strategy.

Steph

Ps hope everything is going well.

**Comment by dssquared** [comment]
The variable for the depth of the box is not declared so I am going to fix
that first then there is a divide by zero error in the driver I hope goes
away once I get the solution trial working.

**Comment by SMcLaren09** [comment]
Try Paxton's driver. In class he said it was not the same as Alex's and it
was what he would be using to grade

**Comment by dssquared** [comment]
I'm stil getting some errors with parts of the code that are for a 3d box.
I'll try paxtons driver.

**Comment by dssquared** [comment]
I will have to wait till I get home to continue working on the program. I'm
hopeing to just set the depth to 1 and leave in thr stuff for 3 dimensions.
I'm just making it a mess trying to remove the depth portion.

**Comment by SMcLaren09** [comment]
Reading Paxton's notes I realized what you meant by 3d. I used width and
height for dimensions because they make sense to me. To most people it
should be width and length.   Anyway I am pitting together the summary and
will get it pushed ASAP. Is there anything else that needs to be done?

**Comment by dssquared** [comment]
There is a hight and width and that's what I was trying to use but there is
a depth used in a couple places and I was trying to remove it without
breaking thr rest of the program. I am almost home and I will try to set
the depth to 1 and see if it works. I think it would be too much work to
remove the depth without rewriting a lot. So it is back to your last push
with one of the depth lines commented out but it throws errors. I'll let
you know how it goes and we can submit.

**Comment by SMcLaren09** [comment]
You should see a pull request. I corrected the code referring to depth and
added the summary. I did not want to commit the changes to master and risk
screwing up any of your changes.

**Comment by dssquared** [comment]
Okay, getting ready to look at it now, just got home.

**Comment by dssquared** [comment]
Now I'm getting errors in their files. I'll look at it for a bit but don't
know what else to do. I think your code is good after removing the depth
and fixing a simple typo. I feel bad I couldn't help more and wish I hadn't
had so much to do at work the last couple weeks.

**Comment by SMcLaren09** [comment]
Do not feel bad. Life happens and it is not always easy. Paxton just
extended the due date to Friday night due to the differences in drivers.  Say
hi to your daughter and get some sleep, we can wrap this up tomorrow.

**Comment by dssquared** [comment]
I have most the day tomorrow and a good part of Friday to work on it. I'll
wait before I push the changes. Right now I have the new driver and might
revert between drivers to help troubleshoot. Im getting an error in a
different place now with the new driver. My daughter gave me the biggest
hug when I got home and is now sleeping in my lap as I work on this. An
extended due date is the best news I can get right now.
Have a good evening and I'll talk to ya tomorrow.

**Comment by SMcLaren09** [comment]
I know that feeling :)

**Pull request merged**
